# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
  colors = true
  interval = 1
  markup = "pango"
  color_good = "#89b4fa"
  color_degraded = "#6e6c7e"
  color_bad = "#f28fad"
}

order += "ipv6"
order += "cpu_temperature 0"
order += "memory"
order += "disk /home"
order += "disk /"
order += "volume master"
order += "wireless _first_"
order += "ethernet _first_"
order += "load"
order += "tztime local"

ipv6 {
  format_up = "IPv6: %ipv6"
  format_down = "IPv6: down"
}

cpu_temperature 0 {
  format = "CPU Temp: %degrees °C"
  path = "/run/cpu_temp"
  color_degraded = "#f5a97f"
}

wireless _first_ {
  format_up = "W: (%quality) %ip"
  format_down = "W: down"
}

ethernet _first_ {
  format_up = "E: %ip (%speed)"
  format_down = "E: down"
}

load {
  format = "Hot Loads: %1min"
}

volume master {
  format = "Vol: %volume"
  format_muted = "Vol (Muted): %volume"
  device = "default"
  mixer = "Master"
  mixer_idx = 0
}

memory {
  format = "Mem: %used/%total (%percentage_used)"
  threshold_degraded = "70%"
}

tztime local {
  format = "<span foreground='#89b4fa'>%Y-%m-%d %H:%M:%S</span>"
}

disk "/" {
  format = "<span foreground='#89b4fa'>Rest of the disk available: %avail (%percentage_used)</span>"
}

disk "/home" {
  format = "<span foreground='#89b4fa'>Home folder: %avail (%percentage_used)</span>"
}
